version: "3"

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./data/data.sql:/docker-entrypoint-initdb.d/data.sql